# Generated by Django 4.0.5 on 2022-07-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('city', models.CharField(blank=b'I01\n', max_length=30)),
                ('email', models.CharField(blank=b'I01\n', max_length=30)),
                ('dob', models.DateField()),
                ('address', models.TextField(blank=b'I01\n')),
            ],
        ),
    ]
